AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sam template for s3 video upload

Resources:
  # My api gateway
  MyAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"

  # My s3 bucket to store uploaded files
  MyS3Bucket:
    Type: AWS::S3::Bucket

  # My lambda function
  MyLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/s3-upload
      Handler: app.handler
      Timeout: 3
      Runtime: nodejs22.x
      Architectures:
        - arm64
      LoggingConfig:
        LogFormat: JSON
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
      Environment:
        Variables:
          BUCKET_NAME: !Ref MyS3Bucket
      Events:
        PresignedUrlCreator:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPIGateway
            Path: /url
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

Outputs:
  PresignedUrl:
    Description: This is the url to get presigned url
    Value: !Sub "https://${MyAPIGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/url"
